#!/usr/bin/env python3
"""Render a text string to single-line g-code using a Hershey stroke font.

Uses the `pyhershey` library, which exposes per-glyph advance-width metrics
(unlike the QCAD CXF format, which strips the original Hershey left/right
margins and falls back to a single global LetterSpacing). The result is
naturally kerned spacing rather than a fixed-width gap between letters.

Glyphs are emitted as pen-up / pen-down polyline runs intended to be streamed
to the MDX-40A via the existing `rollingmill --file <out.gcode>` TUI flow.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from pyhershey import glyph_factory


DEFAULT_FONT = "roman_simplex"


def available_fonts() -> list[str]:
    """Sorted list of pyhershey font names with ASCII coverage."""
    return sorted(glyph_factory.ascii_mappings)


@dataclass
class GCodeOpts:
    height_mm: float = 10.0
    x0: float = 0.0
    y0: float = 0.0
    feed: float = 200.0
    plunge_feed: float = 50.0
    z_safe: float = 2.0
    z_cut: float = -0.1
    return_home: bool = False
    workspace: str | None = None  # e.g. "G54".."G59"; emitted in header if set
    spindle_rpm: int = 10000      # S word value, emitted with M03
    letter_spacing_mm: float = 0.0  # additive gap after each glyph's advance


def _fmt(v: float) -> str:
    """Format a number with up to 3 decimal places, trimmed."""
    s = f"{v:.3f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"


def _fmtp(v: float) -> str:
    """Format a position value: up to 3 decimal places, always at least 1."""
    s = f"{v:.3f}"
    if "." in s:
        s = s.rstrip("0")
        if s.endswith("."):
            s += "0"
    if s == "-0.0":
        s = "0.0"
    return s


def _cap_height(font_name: str) -> float:
    """Bounding-box height of capital H, used to scale font units to mm."""
    g = glyph_factory.from_ascii("H", font_name)
    (_, ymin), (_, ymax) = g.bounding_box
    return ymax - ymin


def _try_glyph(ch: str, font_name: str):
    """Return a GlyphView for `ch`, or None if the character is unsupported."""
    try:
        return glyph_factory.from_ascii(ch, font_name)
    except (ValueError, KeyError):
        return None


def emit_gcode(text: str, font_name: str, opts: GCodeOpts) -> str:
    """Render `text` as g-code using the named Hershey font."""
    cap = _cap_height(font_name)
    scale = opts.height_mm / cap if cap > 0 else 1.0
    out: list[str] = []
    w = out.append

    w("(Generated by utils/text_to_gcode.py)")
    w(f"(Text: {text!r})")
    w(f"(Font: {font_name}, cap height: {opts.height_mm} mm, scale: {_fmt(scale)})")
    w("%")
    w("O00000001")
    w("G21")  # mm
    w("G90")  # absolute
    w("G17")  # XY plane
    if opts.workspace:
        w(opts.workspace)  # workspace offset (G54..G59)
    w(f"F{_fmtp(opts.feed)}")
    w(f"S{opts.spindle_rpm}")
    w("M03")  # spindle on (CW)
    w(f"G00 Z{_fmtp(opts.z_safe)}")

    cursor_x = opts.x0
    base_y = opts.y0
    space = _try_glyph(" ", font_name)
    space_advance_mm = (space.advance_width * scale) if space else opts.height_mm * 0.5

    for ch in text:
        if ch == "\n":
            base_y -= opts.height_mm * 1.5
            cursor_x = opts.x0
            continue
        if ch == "\t":
            cursor_x += space_advance_mm * 4
            continue

        glyph = _try_glyph(ch, font_name)
        if glyph is None:
            # Unsupported character: advance by a space width.
            cursor_x += space_advance_mm + opts.letter_spacing_mm
            continue

        for segment in glyph.segments:
            if len(segment) < 2:
                continue
            sx, sy = segment[0]
            w(f"G00 X{_fmtp(cursor_x + sx * scale)} Y{_fmtp(base_y + sy * scale)}")
            w(f"G01 Z{_fmtp(opts.z_cut)} F{_fmtp(opts.plunge_feed)}")
            w(f"F{_fmtp(opts.feed)}")
            for x, y in segment[1:]:
                w(f"G01 X{_fmtp(cursor_x + x * scale)} Y{_fmtp(base_y + y * scale)}")
            w(f"G00 Z{_fmtp(opts.z_safe)}")

        cursor_x += glyph.advance_width * scale + opts.letter_spacing_mm

    w(f"G00 Z{_fmtp(opts.z_safe)}")
    if opts.return_home:
        w("G00 X0.0 Y0.0")
    w("M05")
    w("M30")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    fonts = available_fonts()
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--text", help="String to render (omit with --list-fonts)")
    p.add_argument("--out", type=Path, help="Output .gcode file path")
    p.add_argument("--font", default=DEFAULT_FONT, choices=fonts,
                   metavar="NAME",
                   help=f"Hershey font name (default: {DEFAULT_FONT}). "
                        f"Use --list-fonts to see all {len(fonts)} options.")
    p.add_argument("--list-fonts", action="store_true",
                   help="Print available font names and exit")
    p.add_argument("--height", type=float, default=10.0,
                   help="Cap height in mm (default 10.0)")
    p.add_argument("--x0", type=float, default=0.0,
                   help="Start X in mm (default 0.0)")
    p.add_argument("--y0", type=float, default=0.0,
                   help="Start Y in mm (default 0.0)")
    p.add_argument("--feed", type=float, default=200.0,
                   help="Cutting feed mm/min (default 200)")
    p.add_argument("--plunge-feed", type=float, default=50.0,
                   help="Z plunge feed mm/min (default 50)")
    p.add_argument("--z-safe", type=float, default=2.0,
                   help="Pen-up Z height mm (default 2.0)")
    p.add_argument("--z-cut", type=float, default=-0.1,
                   help="Pen-down Z depth mm (default -0.1)")
    p.add_argument("--return-home", action="store_true",
                   help="Append G0 X0 Y0 at end of program")
    p.add_argument("--workspace", default=None,
                   choices=["G54", "G55", "G56", "G57", "G58", "G59"],
                   help="Workspace offset to select in header (e.g. G54)")
    p.add_argument("--spindle-rpm", type=int, default=10000,
                   help="Spindle speed in RPM, emitted with M03 (default 10000)")
    p.add_argument("--letter-spacing", type=float, default=0.0,
                   help="Extra mm of gap after each glyph's natural advance "
                        "(default 0.0). Negative values tighten spacing.")
    args = p.parse_args(argv)

    if args.list_fonts:
        for f in fonts:
            print(f)
        return 0

    if not args.text or not args.out:
        p.error("--text and --out are required (unless --list-fonts is given)")

    opts = GCodeOpts(
        height_mm=args.height,
        x0=args.x0, y0=args.y0,
        feed=args.feed, plunge_feed=args.plunge_feed,
        z_safe=args.z_safe, z_cut=args.z_cut,
        return_home=args.return_home,
        workspace=args.workspace,
        spindle_rpm=args.spindle_rpm,
        letter_spacing_mm=args.letter_spacing,
    )
    gcode = emit_gcode(args.text, args.font, opts)
    args.out.write_text(gcode)
    print(f"wrote {args.out} ({len(gcode.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
